POST http://localhost:3000/users
Content-Type: application/json

{
 "name": "Gabriel",
 "phoneNumber": "329434343",
 "email": "gabrielsresende18@gmail.com",
 "wage": 5500, 
 "sector": "Tecnologia" ,
 "status": "ATIVO",
 "password": "gabriel1"
 
}

###
GET http://localhost:3000/users

###
POST http://localhost:3000/autenticate
Content-Type: application/json

{
  "email": "jandeffigueiredo@gmail.com",
  "password": "jande"
}

//franchises

###
PUT http://localhost:3000/franchises
Content-Type: application/json

{
  "email": "vanessamuel@gmail.com",
  "password": "vanessa1"
}